# Core Settings
rpc_url: "https://api.mainnet-beta.solana.com"
jupiter_api_key: "your_jupiter_key_here"
token_address: "your_token_mint_address_here"
dexes: ["Raydium", "Orca", "PumpFun"]
trading_mode: "mixed"

# AI Parameters
ai_parameters:
  model_type: "lstm"
  hidden_size: 128
  training_epochs: 100
  buy_sell_ratio: 0.7
  risk_tolerance: 0.6
  volatility_scaling: true

# AMM Configuration
amm_config:
  strategy: "adaptive"
  initial_price: 0.01
  price_range_min: 0.005
  price_range_max: 0.02
  liquidity_depth: 5000.0
  max_slippage: 1.5
  fee_rate: 0.003

# Strategy Weights
strategies:
  volume_boosting:
    enabled: true
    max_frequency: 15
    buy_sell_ratio: 0.7
  amm:
    enabled: true
    strategy: "adaptive"
  mixed:
    enabled: true
    strategy_weights:
      volume_boosting: 0.4
      wallet_rotation: 0.3
      amm: 0.3
